#!/bin/sh

if (exec < /dev/tty) ; then
  exec >/dev/tty 2>&1;
fi

branch=$(git rev-parse --abbrev-ref HEAD)
if [ "$branch" = "main" ]; then
  ./node_modules/.bin/lint-staged --config ./config/husky/lint-staged.config.js
fi
