autoInstallPeers: true
saveExact: true
minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - 'typescript'
  - 'typescript-eslint'
  - '@typescript-eslint/*'
  - '@typescript/native-preview*'
  - fast-uri@3.1.4

overrides:
  'brace-expansion@5.0.5': '>=5.0.7'
  fast-uri@3: '>=3.1.4 <4.0.0'
  js-yaml: '>=4.1.2'

trustPolicy: no-downgrade
