autoInstallPeers: true
saveExact: true
minimumReleaseAge: 7200
minimumReleaseAgeExclude:
  - 'typescript'
  - 'typescript-eslint'
  - '@typescript-eslint/*'
  - '@typescript/native-preview*'

overrides:
  fast-uri: '3.1.2'
  'brace-expansion@5.0.5': '>=5.0.6'

trustPolicy: no-downgrade
