import lazyGetterNameMatch from "./lazy-getter-name-match.js";

export default {
  meta: {
    name: "eslint-plugin-tabmix",
    version: "1.2.0",
  },
  environments: {
    "extensions": {
      //
      TabView: false,
    },
    "extensions-js": {
      bgSaverPref: false,
      CHROMATABS: false,
      closeallOverlay: false,
      com: false,
      contentAreaDNDObserver: false,
      faviconize: false,
      FdUtils: false,
      FireGestures: false,
      foxTab: false,
      gFxWeaveGlue: false,
      IeTab2: false,
      Local_Install: false,
      mgBuiltInFunctions: false,
      MouseControl: false,
      objLinkify: false,
      PersonaController: false,
      rdrb: false,
      readPref: false,
      RSSTICKER: false,
      SecondSearchBrowser: false,
      SpeedDial: false,
      tileTabs: false,
      TreeStyleTabWindowHelper: false,
      TreeStyleTabBrowser: false,
    },
    "tabmix": {
      gTMPprefObserver: true,
      Tabmix: true,
      TabmixAllTabs: true,
      TabmixContext: true,
      TabmixProgressListener: true,
      TabmixSvc: true,
      TabmixTabbar: true,
      TabmixTabClickOptions: true,
      TMP_BrowserOpenTab: true,
      TMP_ClosedTabs: true,
      TMP_eventListener: true,
      TMP_extensionsCompatibility: true,
      TMP_LastTab: true,
      TMP_Places: true,
      TMP_SessionStore: true,
      TMP_tabDNDObserver: true,
      TMP_undocloseTabButtonObserver: true,

      gZenWorkspaces: true,
      gZenVerticalTabsManager: true,

      // manually added globals to fix no-undef errors
      Overlays: false,
      ChromeManifest: false,
      PreferencesLoader: false,
      TabmixWidgets: false,
      ScriptsLoader: false,
      shortcutKeyMapPromise: false,
      TabmixUtils: false,
      LinkNodeUtils: false,
      ContentSvc: false,
      BrowserUtils: false,
      E10SUtils: false,
      ContextMenu: false,
    },
    "preferences": {
      $: false,
      $Pref: false,
      $Pane: false,
      gAppearancePane: false,
      getFormattedKey: false,
      gMenuPane: false,
      gNumberInput: false,
      gPrefWindow: false,
      gPreferenceList: false,
      MozXULElement: false,
      RTL_UI: false,
      Services: false,
      Shortcuts: false,
      Tabmix: false,
      TabmixSvc: false,
    },
  },
  rules: {
    "lazy-getter-name-match": lazyGetterNameMatch,
  },
};
