/* eslint strict: 0, object-curly-newline: [2, always] */

module.exports = {
  environments: {
    extensions: {
      TabView: false
    },
    "extensions-js": {
      abcdefghijklmnsopqrstuxyz: true,
      bgSaverPref: false,
      CHROMATABS: false,
      closeallOverlay: false,
      com: false,
      contentAreaDNDObserver: false,
      faviconize: false,
      FdUtils: false,
      FireGestures: false,
      foxTab: false,
      gFxWeaveGlue: false,
      IeTab2: false,
      Local_Install: false,
      mgBuiltInFunctions: false,
      MouseControl: false,
      objLinkify: false,
      PersonaController: false,
      rdrb: false,
      readPref: false,
      RSSTICKER: false,
      SecondSearchBrowser: false,
      SpeedDial: false,
      tileTabs: false,
      TreeStyleTabWindowHelper: false,
      TreeStyleTabBrowser: false,
    },
    tabmix: {
      gTMPprefObserver: true,
      Tabmix: true,
      TabmixAllTabs: true,
      TabmixChromeUtils: true,
      TabmixContext: true,
      TabmixProgressListener: true,
      TabmixSessionData: true,
      TabmixSessionManager: true,
      TabmixSvc: true,
      TabmixTabbar: true,
      TabmixTabClickOptions: true,
      TMP_BrowserOpenTab: true,
      TMP_ClosedTabs: true,
      TMP_eventListener: true,
      TMP_extensionsCompatibility: true,
      TMP_LastTab: true,
      TMP_Places: true,
      TMP_SessionStore: true,
      TMP_tabDNDObserver: true,
      TMP_TabView: true,
      TMP_undocloseTabButtonObserver: true,
    },
    preferences: {
      $: false,
      gAppearancePane: false,
      getFormattedKey: false,
      gMenuPane: false,
      gNumberInput: false,
      gPrefWindow: false,
      MozXULElement: false,
      RTL_UI: false,
      Services: false,
      Shortcuts: false,
      Tabmix: false,
      TabmixChromeUtils: true,
      TabmixSvc: false,
    },
    dialog: {
      centerWindowOnScreen: false,
      moveToAlertPosition: false,
      Tabmix: false,
      TabmixSvc: false,
    },
  },
  rules: {
    "import-globals": require("./import-globals"),
    "use-mjs-modules": require("./use-mjs-modules"),
    "valid-lazy": require("./valid-lazy"),
  },
};
