name: bitbucket_upload

on:
  push:
    branches: [ wip/build-xpi ]

env:
  XPI_NAME: tabmix-dev-build

jobs:
  upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          # fix this to main when we push this branch to main
          ref: wip/build-xpi

      - name: Set version in install.rdf
        run: |
          function next_version() {
            local version=$(git tag --sort=-creatordate | grep -E '^v[0-9]+\.[0-9]+\.[0-9]+' | head -n 1 | cut -c 2-)
            if [[ $version =~ ^([0-9]+\.[0-9]+\.[0-9]+-pre\.)([0-9]+)$ ]]; then
              local prefix=${BASH_REMATCH[1]}
              local number=${BASH_REMATCH[2]}
              let "number++"
              echo "${prefix}${number}"
            else
              local IFS='.'
              local -a parts=($version)
              let "parts[-1]++"
              echo "${parts[*]}"
            fi
          }
          version=$(next_version)
          date=$(date +'%Y%m%d.%H%M')
          sed -i "s/1.0.0-unbundeled/$version-$date/" addon/install.rdf
          echo "next version: $version-$date"

      - name: Zip addon folder
        run: |
          cd addon
          zip -rq /tmp/${{ env.XPI_NAME }}.xpi *

      - name: Upload dev-build to bitbucket
        run: |
          curl --request POST \
          --url 'https://api.bitbucket.org/2.0/repositories/onemen/tabmixplus-for-firefox/downloads' \
          --header 'Authorization: Bearer ${{ secrets.BITBUCKET_ACCESS_TOKEN }}' \
          -F 'files=@/tmp/${{ env.XPI_NAME }}.xpi'
